language: rust

os:
    - linux
    - osx

rust:
    - nightly
    - beta
    - stable

cache:
    directories:
        - target

script:
    - cargo build
    - cargo test
    - cargo doc

after_success:
    test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $TRAVIS_RUST_VERSION == "stable" &&
    sh etc/deploy-docs.sh
